import Constants from "expo-constants";
import { Platform } from "react-native";

export const getApiUrl = () => {
    // ---------------------------------------------------------
    // If you are using a tunnel (like localtunnel or ngrok),
    // paste the URL here to bypass local network issues:
                    const TUNNEL_URL = "https://nine-geckos-sell.loca.lt"; // Auto-generated by start-with-tunnel.js
    // ---------------------------------------------------------

    if (TUNNEL_URL) return TUNNEL_URL;

    // For Web, assume localhost or relative path
    if (Platform.OS === "web") {
        return "http://localhost:5000";
    }

    // For Expo Go, get the host URI (machine's IP)
    const hostUri = Constants.expoConfig?.hostUri;
    if (hostUri) {
        const ip = hostUri.split(":")[0];
        return `http://${ip}:5000`;
    }

    // Fallback for Simulators (Android uses 10.0.2.2, iOS uses localhost)
    if (Platform.OS === "android") {
        return "http://10.0.2.2:5000";
    }

    return "http://localhost:5000";
};
